import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "en" | "es" | "fr" | "zh" | "ar";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => any;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("en");

  const isRTL = language === "ar";

  useEffect(() => {
    document.documentElement.dir = isRTL ? "rtl" : "ltr";
    document.documentElement.lang = language;
  }, [language, isRTL]);

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      <div dir={isRTL ? "rtl" : "ltr"}>{children}</div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};

export const translations: Record<Language, any> = {
  en: {
    nav_why: "Why Oh Curio!",
    nav_features: "Features",
    nav_pilot: "Pilot",
    nav_join: "Join the Pilot Program",
    nav_about: "About Us",
    hero_tag: "Oh Curio!",
    hero_title: "The patron engagement platform public libraries have been waiting for.",
    hero_subtitle: "",
    hero_cta: "Join the Pilot Program",
    hero_desc: "Reconnect your library with the community it serves. Oh Curio! helps libraries engage patrons through meaningful, personalized communication .",
    prob_title: "Libraries deserve better tools",
    prob_label: "The Problem",
    prob_p1: "Patron engagement relies on outdated flyers and generic emails",
    prob_p2: "Libraries struggle to reach the right people with the right programs",
    prob_p3: "Communication feels impersonal and one-directional",
    prob_p4: "Valuable community feedback goes uncollected",
    sol_label: "The Oh Curio! Way",
    sol_p1: "Personalized outreach that matches patrons with relevant programs",
    sol_p2: "Two-way communication that builds real community connections",
    sol_p3: "Smart insights that help libraries understand what patrons actually want",
    sol_p4: "Simple tools that save staff time and increase impact",
    feat_title: "Tools that make library communication feel human",
    feat_desc: "Designed for forward-thinking public libraries.",
    feat_trust: "Designed for forward-thinking public libraries.",
    feat_1_title: "Smart Notifications",
    feat_1_desc: "Send the right message to the right patron at the right time.",
    feat_2_title: "Self-Service Checkout",
    feat_2_desc: "Empower patrons to check out materials independently from their device.",
    feat_3_title: "Family Card Hub",
    feat_3_desc: "Manage all family library accounts from a centralized dashboard.",
    feat_4_title: "Events & Registration",
    feat_4_desc: "Help patrons find and register for programs they'll actually attend.",
    feat_5_title: "Staff Dashboard",
    feat_5_desc: "See what's working and where engagement is growing instantly.",
    feat_6_title: "Multilingual Support",
    feat_6_desc: "English, Spanish, French, Mandarin, Arabic (RTL support). Built for the communities that are already your patrons.",
    form_title: "Bring Oh Curio! to your library",
    form_subtitle: "Join our pilot program and be among the first libraries to transform patron engagement.",
    form_notice: "Now accepting pilot applications - limited spots available",
    form_name: "Name *",
    form_name_placeholder: "Your name",
    form_lib: "Library Name *",
    form_lib_placeholder: "Your library",
    form_email: "Email *",
    form_email_placeholder: "you@library.org",
    form_msg: "Message",
    form_msg_placeholder: "Anything you'd like us to know",
    form_cta: "Join the Pilot Program",
    form_submitting: "Submitting...",
    form_success: "Thank you — we'll be in touch shortly.",
    form_footer: "We'll reach out personally to schedule your onboarding.",
    footer_rights: "© 2026 Capital Breaks LLC. All rights reserved.",
    card_1_label: "Coming up Tomorrow",
    card_1_title: "Seed Library Workshop",
    card_1_desc: "Join us @ 10:00 AM in the Community Garden",
    card_2_label: "Ready for Pickup",
    card_2_title: "The Midnight Library",
    card_2_desc: "Main branch · Pickup available until 8:00 PM",
    card_3_label: "Personalized for you",
    card_3_title: "New Photography Collection",
    card_3_desc: "Based on your recent interest in Art & Design",
    ui_old_way: "The Old Way",
    ui_sys_notif: "System Notification",
    ui_barcode: "Barcode notice",
    ui_status: "Status",
    ui_queue: "Queue system",
    ui_alert: "Alert",
    ui_7days: "7 days warning",
    ui_curio_way: "The Oh Curio! Way",
    ui_pers_msg: "Personalized Message",
    ui_spare: '"Spare is waiting for you"',
    ui_act_time: "Add more time",
    ui_pickup: "Pickup by Friday",
    ui_renew: "Tap to renew",
    ui_before_msg: "NOTICE: Item barcode #39153030842740 has reached the front of the request queue. Please collect within 7 days or your hold will be cancelled.",
    ui_after_msg: "Spare is waiting for you! Pickup by Friday. Tap to renew or let us know if you need more time.",
    // --- About Section ---
    about_tag: "ABOUT Oh Curio!",
    about_title_1: "Built by a library patron.",
    about_title_2: "Right here in Sparta, NJ.",
    about_gallery_cap_1: "Her first Sparta Public Library card.",
    about_gallery_cap_2: "The family that reads together.",
    about_gallery_cap_3: "In his element. Young Adults section.",
    about_story_p1: "Oh Curio! was built by a Sparta resident, public library patron, and product professional who spent years raising two readers — and years getting notifications like this from the Main Library Alliance:",
    about_notif_quote: '"You have 2 library items due today." — circ-sparta · Main Library Alliance',
    about_story_p2: "No one-tap renewal. No way to act on it. Just a notification that ends in a dead end — from an institution that matters deeply to our family. The question became unavoidable:",
    about_badge_1_l1: "Trademarked",
    about_badge_1_l2: "USPTO · Class 42",
    about_badge_2_l1: "Privacy-first",
    about_badge_2_l2: "NJ statute compliant",
    about_badge_3_l1: "Local",
    about_badge_3_l2: "Sparta, NJ",
    about_directors_link: "Common Questions from Library Directors",
    // --- FAQ Section ---
    faq_q1_badge: "KOHA ✓",
    faq_q1_title: "Does Oh Curio! work with Koha?",
    faq_q1_body: "Yes — Koha was our first integration priority. Oh Curio! connects directly to Koha's REST API using OAuth2 authentication. If your library is running Koha, the integration pathway is already designed, documented, and ready to implement. No custom development is required on your end.",
    faq_q2_title: "What does implementation look like for a library our size?",
    faq_q2_body: "Three steps: your IT staff enables the REST API in Koha's system preferences (a single checkbox), generates an API key, and shares it with us. We handle everything else — catalog sync, notification setup, patron onboarding, and staff training. Most libraries are live within 30 days.",
    faq_q3_badge: "GRANT-FUNDABLE",
    faq_q3_title: "What does it cost?",
    faq_q3_body: "Oh Curio! is priced at approximately $1 per active cardholder per year. Most libraries qualify for LSTA grant funding ask us about it in the pilot application. We provide a ready-made application template to every pilot partner. Many libraries can launch at zero direct budget cost.",
    faq_q4_title: "How much work is this for our staff?",
    faq_q4_body: "We designed Oh Curio! specifically for libraries with limited IT resources — including libraries with no dedicated IT staff. The admin panel has a guided setup checklist and we provide hands-on onboarding throughout. After launch, day-to-day operation requires no technical maintenance from your team.",
    faq_q5_title: "What ILS systems do you support beyond Koha?",
    faq_q5_body: "Koha is our pilot integration. Polaris, Sierra, and Evergreen are next on the roadmap. Running something else? Tell us in the pilot application — we're actively prioritizing based on partner needs.",
    faq_footer_title: "Most libraries can pilot Oh Curio! at no direct budget cost.",
    faq_footer_body: "Federal LSTA grant funding — administered through your State Library — is available specifically for patron technology projects. We provide a ready-made grant application template to every pilot partner. Ask us about it in the form below.",
  },

  es: {
    nav_why: "¿Por qué Oh Curio!",
    nav_features: "Funciones",
    nav_pilot: "Piloto",
    nav_join: "Unirse al Piloto",
    nav_about: "Sobre Nosotros",
    hero_tag: "Una plataforma de participación para bibliotecas públicas",
    hero_title: "¡Oh Curio!",
    hero_subtitle: "Haz que cada mensaje sea leído por tus usuarios.",
    hero_cta: "Solicitar Acceso Temprano",
    hero_desc: "Reconecta tu biblioteca con la comunidad a la que sirve. Oh Curio! ayuda a las bibliotecas a interactuar con los usuarios a través de una comunicación significativa y personalizada, sin esfuerzo.",
    prob_title: "Las bibliotecas merecen mejores herramientas",
    prob_label: "El Problema",
    prob_p1: "La participación de los usuarios depende de folletos obsoletos y correos genéricos",
    prob_p2: "Las bibliotecas luchan por llegar a las personas adecuadas con los programas adecuados",
    prob_p3: "La comunicación se siente impersonal y unidireccional",
    prob_p4: "Los valiosos comentarios de la comunidad no se recopilan",
    sol_label: "El estilo Oh Curio!",
    sol_p1: "Alcance personalizado que conecta a los usuarios con programas relevantes",
    sol_p2: "Comunicación bidireccional que construye conexiones comunitarias reales",
    sol_p3: "Información inteligente que ayuda a las bibliotecas a entender lo que los usuarios realmente quieren",
    sol_p4: "Herramientas simples que ahorran tiempo al personal y aumentan el impacto",
    feat_title: "Herramientas que hacen que la comunicación bibliotecaria se sienta humana",
    feat_desc: "Designed for forward-thinking public libraries.",
    feat_trust: "Designed for forward-thinking public libraries.",
    feat_1_title: "Comprende lo que les importa a tus usuarios",
    feat_1_desc: "Comprende intereses y preferencias para adaptar cada interacción.",
    feat_2_title: "Envía mensajes que la gente realmente abra",
    feat_2_desc: "Envía el mensaje correcto a la persona adecuada en el momento justo.",
    feat_3_title: "Descubrimiento de eventos",
    feat_3_desc: "Ayuda a los usuarios a encontrar programas que realmente asistirán y amarán.",
    feat_4_title: "Bucles de retroalimentación",
    feat_4_desc: "Recopila comentarios en tiempo real para mejorar los servicios bibliotecarios.",
    feat_5_title: "Mira lo que funciona al instante",
    feat_5_desc: "Mira qué está funcionando y dónde está creciendo el compromiso.",
    feat_6_title: "Soporte multilingüe",
    feat_6_desc: "Inglés, español, francés, mandarín, árabe (soporte RTL). Creado para las comunidades que ya son sus usuarios.",
    form_title: "Lleva Oh Curio! a tu biblioteca",
    form_subtitle: "Únete a nuestro programa piloto y sé de las primeras bibliotecas en transformar la participación de los usuarios.",
    form_notice: "Los cupos piloto son limitados — acceso temprano para bibliotecas seleccionadas.",
    form_name: "Nombre *",
    form_name_placeholder: "Tu nombre",
    form_lib: "Nombre de la Biblioteca *",
    form_lib_placeholder: "Tu biblioteca",
    form_email: "Correo electrónico *",
    form_email_placeholder: "tu@biblioteca.org",
    form_msg: "Mensaje",
    form_msg_placeholder: "Algo que quieras que sepamos",
    form_cta: "Solicitar Piloto",
    form_submitting: "Enviando...",
    form_success: "Gracias, nos pondremos en contacto pronto.",
    form_footer: "Nos comunicaremos personalmente para programar su incorporación.",
    footer_rights: "© 2026 Capital Breaks LLC. All rights reserved.",
    card_1_label: "Mañana",
    card_1_title: "Taller de Semilleros",
    card_1_desc: "Acompáñanos a las 10:00 AM en el Jardín Comunitario",
    card_2_label: "Listo para Recoger",
    card_2_title: "La Biblioteca de la Medianoche",
    card_2_desc: "Sucursal principal · Recogida disponible hasta las 8:00 PM",
    card_3_label: "Personalizado para ti",
    card_3_title: "Nueva Colección de Fotografía",
    card_3_desc: "Basado en tu reciente interés en Arte y Diseño",
    ui_old_way: "La Forma Antigua",
    ui_sys_notif: "Notificación del Sistema",
    ui_barcode: "Aviso de código de barras",
    ui_status: "Estado",
    ui_queue: "Sistema de cola",
    ui_alert: "Alerta",
    ui_7days: "Aviso de 7 días",
    ui_curio_way: "El Estilo Oh Curio!",
    ui_pers_msg: "Mensaje Personalizado",
    ui_spare: '"Spare te está esperando"',
    ui_act_time: "Agregar más tiempo",
    ui_pickup: "Recoger antes del viernes",
    ui_renew: "Toca para renovar",
    ui_before_msg: "AVISO: El código de barras #39153030842740 ha llegado al principio de la cola. Por favor recoja en 7 días o se cancelará su retención.",
    ui_after_msg: "¡Spare te está esperando! Recoger antes del viernes. Toca para renovar o avísanos si necesitas más tiempo.",
    // --- About Section ---
    about_tag: "SOBRE Oh Curio!",
    about_title_1: "Creado por un usuario de biblioteca.",
    about_title_2: "Aquí mismo en Sparta, NJ.",
    about_gallery_cap_1: "Su primera tarjeta de la Biblioteca Pública de Sparta.",
    about_gallery_cap_2: "La familia que lee unida.",
    about_gallery_cap_3: "En su elemento. Sección de adultos jóvenes.",
    about_story_p1: "Oh Curio! fue creado por un residente de Sparta, usuario de biblioteca pública y profesional de producto que pasó años criando a dos lectores — y años recibiendo notificaciones como esta de la Main Library Alliance:",
    about_notif_quote: '"Tienes 2 artículos de biblioteca con vencimiento hoy." — circ-sparta · Main Library Alliance',
    about_story_p2: "Sin renovación con un toque. Sin forma de actuar. Solo una notificación que termina en un callejón sin salida — de una institución que importa profundamente a nuestra familia. La pregunta se volvió inevitable:",
    about_badge_1_l1: "Marca registrada",
    about_badge_1_l2: "USPTO · Clase 42",
    about_badge_2_l1: "Privacidad primero",
    about_badge_2_l2: "Cumple estatuto de NJ",
    about_badge_3_l1: "Local",
    about_badge_3_l2: "Sparta, NJ",
    about_directors_link: "Preguntas frecuentes de directores de bibliotecas",
  },

  fr: {
    nav_why: "Pourquoi Oh Curio!",
    nav_features: "Fonctionnalités",
    nav_pilot: "Pilote",
    nav_join: "Rejoindre le Pilote",
    nav_about: "À Propos",
    hero_tag: "Une plateforme d'engagement pour les bibliothèques publiques",
    hero_title: "Oh Curio!",
    hero_subtitle: "Faites en sorte que chaque message soit lu par vos usagers.",
    hero_cta: "Demander un Accès Anticipé",
    hero_desc: "Reconnectez votre bibliothèque avec la communauté qu'elle dessert. Oh Curio! aide les bibliothèques à engager les usagers grâce à une communication significative et personnalisée, sans effort.",
    prob_title: "Les bibliothèques méritent de meilleurs outils",
    prob_label: "Le Problème",
    prob_p1: "L'engagement des usagers repose sur des dépliants obsolètes et des e-mails génériques",
    prob_p2: "Les bibliothèques peinent à atteindre les bonnes personnes avec les bons programmes",
    prob_p3: "La communication semble impersonnelle et unidirectionnelle",
    prob_p4: "Les précieux commentaires de la communauté ne sont pas collectés",
    sol_label: "La Méthode Oh Curio!",
    sol_p1: "Une sensibilisation personnalisée qui associe les usagers aux programmes pertinents",
    sol_p2: "Une communication bidirectionnelle qui crée de réels liens communautaires",
    sol_p3: "Des informations intelligentes qui aident les bibliothèques à comprendre ce que veulent vraiment les usagers",
    sol_p4: "Des outils simples qui font gagner du temps au personnel et augmentent l'impact",
    feat_title: "Des outils qui humanisent la communication en bibliothèque",
    feat_desc: "Designed for forward-thinking public libraries.",
    feat_trust: "Designed for forward-thinking public libraries.",
    feat_1_title: "Comprenez ce qui compte pour vos usagers",
    feat_1_desc: "Comprenez les intérêts et les préférences pour personnaliser chaque interaction.",
    feat_2_title: "Envoyez des messages que les gens ouvrent vraiment",
    feat_2_desc: "Envoyez le bon message à la bonne personne au bon moment.",
    feat_3_title: "Découverte d'événements",
    feat_3_desc: "Aidez les usagers à trouver des programmes qu'ils aimeront et auxquels ils assisteront vraiment.",
    feat_4_title: "Boucles de rétroaction",
    feat_4_desc: "Collectez des avis en temps réel pour améliorer les services de la bibliothèque.",
    feat_5_title: "Voyez ce qui fonctionne instantanément",
    feat_5_desc: "Voyez ce qui fonctionne et où l'engagement progresse.",
    feat_6_title: "Support multilingue",
    feat_6_desc: "Anglais, espagnol, français, mandarin, arabe (support RTL). Conçu pour les communautés qui sont déjà vos usagers.",
    form_title: "Apportez Oh Curio! à votre bibliothèque",
    form_subtitle: "Rejoignez notre programme pilote et faites partie des premières bibliothèques à transformer l'engagement des usagers.",
    form_notice: "Les places pilotes sont limitées — accès anticipé pour les bibliothèques sélectionnées.",
    form_name: "Nom *",
    form_name_placeholder: "Votre nom",
    form_lib: "Nom de la bibliothèque *",
    form_lib_placeholder: "Votre bibliothèque",
    form_email: "E-mail *",
    form_email_placeholder: "vous@bibliotheque.org",
    form_msg: "Message",
    form_msg_placeholder: "Tout ce que vous aimeriez nous dire",
    form_cta: "Postuler pour le Pilote",
    form_submitting: "Envoi en cours...",
    form_success: "Merci — nous vous contacterons prochainement.",
    form_footer: "Nous vous contacterons personnellement pour planifier votre intégration.",
    footer_rights: "© 2026 Capital Breaks LLC. All rights reserved.",
    card_1_label: "Demain",
    card_1_title: "Atelier Bibliothèque de Semences",
    card_1_desc: "Rejoignez-nous à 10h00 au Jardin Communautaire",
    card_2_label: "Prêt pour le Retrait",
    card_2_title: "La Bibliothèque de Minuit",
    card_2_desc: "Branche principale · Retrait disponible jusqu'à 20h00",
    card_3_label: "Personnalisé pour vous",
    card_3_title: "Nouvelle Collection de Photographie",
    card_3_desc: "Basé sur votre intérêt récent pour l'Art et le Design",
    ui_old_way: "L'Ancienne Méthode",
    ui_sys_notif: "Notification Système",
    ui_barcode: "Avis de code-barres",
    ui_status: "Statut",
    ui_queue: "Système de file d'attente",
    ui_alert: "Alerte",
    ui_7days: "Avertissement de 7 jours",
    ui_curio_way: "La Méthode Oh Curio!",
    ui_pers_msg: "Message Personnalisé",
    ui_spare: '"Spare vous attend"',
    ui_act_time: "Ajouter plus de temps",
    ui_pickup: "Retrait d'ici vendredi",
    ui_renew: "Appuyez pour renouveler",
    ui_before_msg: "AVIS : Le code-barres #39153030842740 a atteint l'avant de la file d'attente. Veuillez le récupérer dans les 7 jours ou la réservation sera annulée.",
    ui_after_msg: "Spare vous attend ! Retrait d'ici vendredi. Appuyez pour renouveler ou dites-nous si vous avez besoin de plus de temps.",
    // --- About Section ---
    about_tag: "À PROPOS D'Oh Curio!",
    about_title_1: "Créé par un usager de bibliothèque.",
    about_title_2: "Ici même à Sparta, NJ.",
    about_gallery_cap_1: "Sa première carte de la Bibliothèque Publique de Sparta.",
    about_gallery_cap_2: "La famille qui lit ensemble.",
    about_gallery_cap_3: "Dans son élément. Section Jeunes Adultes.",
    about_story_p1: "Oh Curio! a été créé par un résident de Sparta, usager de bibliothèque publique et professionnel du produit, qui a passé des années à élever deux lecteurs — et des années à recevoir des notifications comme celle-ci de la Main Library Alliance :",
    about_notif_quote: '"Vous avez 2 articles de bibliothèque à rendre aujourd\'hui." — circ-sparta · Main Library Alliance',
    about_story_p2: "Pas de renouvellement en un tap. Aucun moyen d'agir. Juste une notification sans suite — d'une institution qui compte profondément pour notre famille. La question est devenue inévitable :",
    about_badge_1_l1: "Marque déposée",
    about_badge_1_l2: "USPTO · Classe 42",
    about_badge_2_l1: "Confidentialité d'abord",
    about_badge_2_l2: "Conforme aux statuts du NJ",
    about_badge_3_l1: "Local",
    about_badge_3_l2: "Sparta, NJ",
    about_directors_link: "Questions fréquentes des directeurs de bibliothèques",
  },

  zh: {
    nav_why: "为什么选择 Oh Curio!",
    nav_features: "功能",
    nav_pilot: "试点项目",
    nav_join: "加入试点项目",
    nav_about: "关于我们",
    hero_tag: "公共图书馆的读者互动平台",
    hero_title: "Oh Curio!",
    hero_subtitle: "确保您的每一条消息都被读者阅读。",
    hero_cta: "申请早期访问",
    hero_desc: "重新连接您的图书馆与其服务的社区。Oh Curio! 帮助图书馆通过有意义的、个性化的沟通来吸引读者——毫不费力。",
    prob_title: "图书馆值得更好的工具",
    prob_label: "问题所在",
    prob_p1: "读者互动依赖于过时的传单和通用的电子邮件",
    prob_p2: "图书馆难以通过合适的项目接触到合适的人",
    prob_p3: "沟通感觉缺乏人情味且是单向的",
    prob_p4: "宝贵的社区反馈未被收集",
    sol_label: "Oh Curio! 方式",
    sol_p1: "个性化的外宣，将读者与相关项目匹配",
    sol_p2: "建立真实社区联系的双向沟通",
    sol_p3: "帮助图书馆了解读者真正需求的智能洞察",
    sol_p4: "节省员工时间并增加影响力的简单工具",
    feat_title: "让图书馆沟通充满人情味的工具",
    feat_desc: "Designed for forward-thinking public libraries.",
    feat_trust: "Designed for forward-thinking public libraries.",
    feat_1_title: "了解您的读者关心什么",
    feat_1_desc: "了解兴趣和偏好，以量身定制每一次互动。",
    feat_2_title: "发送人们真正会打开的消息",
    feat_2_desc: "在正确的时间向正确的读者发送正确的信息。",
    feat_3_title: "活动发现",
    feat_3_desc: "帮助读者找到他们真正会参加并喜爱的项目。",
    feat_4_title: "反馈循环",
    feat_4_desc: "收集实时意见以塑造更好的图书馆服务。",
    feat_5_title: "即时查看成效",
    feat_5_desc: "查看哪些措施有效以及参与度在何处增长。",
    feat_6_title: "多语言支持",
    feat_6_desc: "英语、西班牙语、法语、普通话、阿拉伯语 (RTL 支持)。为已经是您的读者的社区而打造。",
    form_title: "将 Oh Curio! 引入您的图书馆",
    form_subtitle: "加入我们的试点计划，成为第一批改变读者互动的图书馆。",
    form_notice: "试点名额有限——为选定的图书馆提供早期访问。",
    form_name: "姓名 *",
    form_name_placeholder: "您的姓名",
    form_lib: "图书馆名称 *",
    form_lib_placeholder: "您的图书馆",
    form_email: "电子邮件 *",
    form_email_placeholder: "you@library.org",
    form_msg: "留言",
    form_msg_placeholder: "任何您想让我们知道的信息",
    form_cta: "申请试点",
    form_submitting: "提交中...",
    form_success: "谢谢——我们会尽快与您联系。",
    form_footer: "我们将亲自与您联系以安排您的入职培训。",
    footer_rights: "© 2026 Capital Breaks LLC. All rights reserved.",
    card_1_label: "明天即将开始",
    card_1_title: "种子图书馆研讨会",
    card_1_desc: "上午 10:00 在社区花园加入我们",
    card_2_label: "待取件",
    card_2_title: "午夜图书馆",
    card_2_desc: "总馆 · 取件时间截止至晚上 8:00",
    card_3_label: "为您定制",
    card_3_title: "新摄影藏品",
    card_3_desc: "基于您最近对艺术与设计的兴趣",
    ui_old_way: "传统方式",
    ui_sys_notif: "系统通知",
    ui_barcode: "条形码通知",
    ui_status: "状态",
    ui_queue: "排队系统",
    ui_alert: "警报",
    ui_7days: "7天警告",
    ui_curio_way: "Oh Curio! 方式",
    ui_pers_msg: "个性化消息",
    ui_spare: '"Spare 正在等您"',
    ui_act_time: "添加更多时间",
    ui_pickup: "周五前取件",
    ui_renew: "点击续借",
    ui_before_msg: "通知：物品条形码 #39153030842740 已到达请求队列的最前面。请在7天内领取，否则您的保留将被取消。",
    ui_after_msg: "Spare 正在等您！周五前取件。点击续借，如果需要更多时间请告诉我们。",
    // --- About Section ---
    about_tag: "关于 Oh Curio!",
    about_title_1: "由一位图书馆读者创建。",
    about_title_2: "就在新泽西州斯巴达市。",
    about_gallery_cap_1: "她的第一张斯巴达公共图书馆卡。",
    about_gallery_cap_2: "一起阅读的家庭。",
    about_gallery_cap_3: "如鱼得水。青少年阅览区。",
    about_story_p1: "Oh Curio! 由一位斯巴达市居民、公共图书馆读者兼产品专业人士创建，他花了多年时间培养两位小读者——也花了多年时间收到来自 Main Library Alliance 的这样的通知：",
    about_notif_quote: '"您今天有 2 件图书馆物品到期。" — circ-sparta · Main Library Alliance',
    about_story_p2: "无法一键续借，无法采取任何行动。只是一条无处着力的通知——来自一个对我们家庭意义深重的机构。这个问题变得无法回避：",
    about_badge_1_l1: "已注册商标",
    about_badge_1_l2: "USPTO · 第42类",
    about_badge_2_l1: "隐私优先",
    about_badge_2_l2: "符合新泽西州法规",
    about_badge_3_l1: "本地",
    about_badge_3_l2: "新泽西州斯巴达市",
    about_directors_link: "图书馆馆长常见问题",
  },

  ar: {
    nav_why: "لماذا أوه كيريو",
    nav_features: "الميزات",
    nav_pilot: "البرنامج التجريبي",
    nav_join: "انضم للبرنامج التجريبي",
    nav_about: "من نحن",
    hero_tag: "منصة لإشراك الرواد للمكتبات العامة",
    hero_title: "أوه كيريو!",
    hero_subtitle: "اجعل كل رسالة يقرأها روادك بالفعل.",
    hero_cta: "طلب وصول مبكر",
    hero_desc: "أعد ربط مكتبتك بالمجتمع الذي تخدمه. يساعد أوه كيريو! المكتبات على إشراك الرواد من خلال تواصل هادف وشخصي - دون عناء.",
    prob_title: "المكتبات تستحق أدوات أفضل",
    prob_label: "المشكلة",
    prob_p1: "يعتمد إشراك الرواد على المنشورات القديمة ورسائل البريد الإلكتروني العامة",
    prob_p2: "تواجه المكتبات صعوبة في الوصول إلى الأشخاص المناسبين بالبرامج المناسبة",
    prob_p3: "يبدو التواصل غير شخصي وفي اتجاه واحد",
    prob_p4: "ردود الفعل المجتمعية القيمة لا يتم جمعها",
    sol_label: "طريقة أوه كيريو!",
    sol_p1: "تواصل شخصي يطابق الرواد مع البرامج ذات الصلة",
    sol_p2: "تواصل ثنائي الاتجاه يبني روابط مجتمعية حقيقية",
    sol_p3: "رؤى ذكية تساعد المكتبات على فهم ما يريده الرواد بالفعل",
    sol_p4: "أدوات بسيطة توفر وقت الموظفين وتزيد من الأثر",
    feat_title: "أدوات تجعل تواصل المكتبة يبدو إنسانياً",
    feat_desc: "Designed for forward-thinking public libraries.",
    feat_trust: "Designed for forward-thinking public libraries.",
    feat_1_title: "افهم ما يهتم به روادك",
    feat_1_desc: "افهم الاهتمامات والتفضيلات لتصميم كل تفاعل.",
    feat_2_title: "أرسل رسائل يفتحها الناس بالفعل",
    feat_2_desc: "أرسل الرسالة الصحيحة للرائد المناسب في الوقت المناسب.",
    feat_3_title: "اكتشاف الفعاليات",
    feat_3_desc: "ساعد الرواد في العثور على البرامج التي سيحضرونها ويحبونها بالفعل.",
    feat_4_title: "حلقات التغذية الراجعة",
    feat_4_desc: "اجمع الملاحظات في الوقت الفعلي لتشكيل خدمات مكتبية أفضل.",
    feat_5_title: "شاهد ما ينجح فوراً",
    feat_5_desc: "تعرف على ما ينجح وأين ينمو التفاعل.",
    feat_6_title: "دعم متعدد اللغات",
    feat_6_desc: "الإنجليزية، الإسبانية، الفرنسية، الماندرين، العربية (دعم RTL). صُمم للمجتمعات التي هي بالفعل من روادك.",
    form_title: "أحضر أوه كيريو! إلى مكتبتك",
    form_subtitle: "انضم إلى برنامجنا التجريبي وكن من بين أوائل المكتبات التي تحول إشراك الرواد.",
    form_notice: "أماكن البرنامج التجريبي محدودة - وصول مبكر لمكتبات مختارة.",
    form_name: "الاسم *",
    form_name_placeholder: "اسمك",
    form_lib: "اسم المكتبة *",
    form_lib_placeholder: "مكتبتك",
    form_email: "البريد الإلكتروني *",
    form_email_placeholder: "you@library.org",
    form_msg: "الرسالة",
    form_msg_placeholder: "أي شيء تود أن نعرفه",
    form_cta: "تقدم للبرنامج التجريبي",
    form_submitting: "جاري الإرسال...",
    form_success: "شكراً لك - سنبقى على تواصل قريباً.",
    form_footer: "سنتواصل معك شخصياً لتحديد موعد انضمامك للمنصة.",
    footer_rights: "© 2026 Capital Breaks LLC. All rights reserved.",
    card_1_label: "غداً",
    card_1_title: "ورشة عمل مكتبة البذور",
    card_1_desc: "انضم إلينا الساعة 10:00 صباحاً في حديقة المجتمع",
    card_2_label: "جاهز للاستلام",
    card_2_title: "مكتبة منتصف الليل",
    card_2_desc: "الفرع الرئيسي · الاستلام متاح حتى الساعة 8:00 مساءً",
    card_3_label: "مخصص لك",
    card_3_title: "مجموعة تصوير فوتوغرافي جديدة",
    card_3_desc: "بناءً على اهتمامك الأخير بالفنون والتصميم",
    ui_old_way: "الطريقة القديمة",
    ui_sys_notif: "إشعار النظام",
    ui_barcode: "إشعار الباركود",
    ui_status: "الحالة",
    ui_queue: "نظام الانتظار",
    ui_alert: "تنبيه",
    ui_7days: "تحذير 7 أيام",
    ui_curio_way: "طريقة أوه كيريو!",
    ui_pers_msg: "رسالة مخصصة",
    ui_spare: '"Spare في انتظارك"',
    ui_act_time: "أضف المزيد من الوقت",
    ui_pickup: "الاستلام بحلول الجمعة",
    ui_renew: "انقر للتجديد",
    ui_before_msg: "إشعار: لقد وصل الباركود #39153030842740 إلى مقدمة قائمة الانتظار. يرجى الاستلام خلال 7 أيام أو سيتم إلغاء الحجز.",
    ui_after_msg: "Spare في انتظارك! الاستلام بحلول الجمعة. انقر للتجديد أو أخبرنا إذا كنت بحاجة إلى مزيد من الوقت.",
    // --- About Section ---
    about_tag: "عن أوه كيريو!",
    about_title_1: "بُني بواسطة رائد مكتبة.",
    about_title_2: "هنا في سبارتا، نيو جيرسي.",
    about_gallery_cap_1: "أول بطاقة مكتبة عامة في سبارتا لها.",
    about_gallery_cap_2: "العائلة التي تقرأ معاً.",
    about_gallery_cap_3: "في بيئته الطبيعية. قسم الشباب.",
    about_story_p1: "بُني أوه كيريو! بواسطة مقيم في سبارتا، ورائد مكتبة عامة، ومحترف في تطوير المنتجات، أمضى سنوات في تربية قارئَين — وسنوات يتلقى إشعارات كهذه من تحالف المكتبات الرئيسي:",
    about_notif_quote: '"لديك 2 عنصر مكتبة مستحق اليوم." — circ-sparta · Main Library Alliance',
    about_story_p2: "لا تجديد بنقرة واحدة. لا طريقة للتصرف. مجرد إشعار ينتهي بطريق مسدود — من مؤسسة تعني الكثير لعائلتنا. أصبح السؤال لا مفر منه:",
    about_badge_1_l1: "علامة تجارية مسجلة",
    about_badge_1_l2: "USPTO · الفئة 42",
    about_badge_2_l1: "الخصوصية أولاً",
    about_badge_2_l2: "متوافق مع قانون نيو جيرسي",
    about_badge_3_l1: "محلي",
    about_badge_3_l2: "سبارتا، نيو جيرسي",
    about_directors_link: "أسئلة شائعة من مديري المكتبات",
  },
};
